### ISSUE TITLE
problems with the new RedisNodeSubscription

### ISSUE THREAD

**Issue by costin** [the-mad-dog/rjc#9]
Hi,

I'm trying out the 0.6.3 release and found some issues with the latest RedisNodeSubscriber:
1. the close() method triggers a NPE if the subscription hasn't started yet:
   subscriber = new RedisNodeSubscriber();
   subscriber.setDataSource(...);
   subscriber.close(); <-- NPE
2. there is no support for adding or removing patterns or channels to the subscription (which Redis supports).
3. the subscription doesn't seem to stop even where are no channels or patterns only when an exception is thrown. The only way I see the subscription being cancelled is by closing the underlying connection which in turn forces an exception to be thrown (potentially) and the subscription to be cancelled.
4. Close() method always closes the underlying connection as well so one cannot reuse it.

Out of these 3 and 4 have the biggest impact and are preventing the use of 6.3.0 - can you please address them?

Thanks,

**Comment by the-mad-dog** [comment]
1,2,3 fixed
I have deployed 0.6.4-SNAPSHOT version with these fixes. Please look at that and tell me you conclusion. Note that there are some changes: subscribe method was renamed to runSubscription, also few new methods have been added.
about 4. If you want to reuse connection you can use poolable data source for that.

**Comment by costin** [comment]
Things are looking good on 0.6.4 - thanks for the quick turnaround.

**Comment by costin** [comment]
Hi,
What's the ETA for the 0.6.4 release?

**Comment by the-mad-dog** [comment]
0.6.4 has been released

**Comment by costin** [comment]
Cool - how long does it take for the Maven artifacts to be published? They don't seem to be currently available...

**Comment by the-mad-dog** [comment]
it should not take more then one hour
